theme: jekyll-theme-hacker  
title: Imminent-Darkness Homepage
description: * United States Army veteran  
* Journeyman Electrician in Oregon and Washington for 10 years  
* B.S. Computer Science from Eastern Oregon University  
* Security Researcher who enjoys learning and writing new security tools  
