remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Steven Wilkins
description:  
include: ['_pages']
markdown: kramdown
excerpt_separator: "\n\n"
kramdown:
  input:  GFM
  
