remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Imminent-Darkness
description: Effective security requires one to reflect on the most terrifying scenario and prepare for someone diabolical enough to execute it.
include: ['_pages']
markdown: kramdown
excerpt_separator: "\n\n"
kramdown:
  input:  GFM
  
