theme: jekyll-theme-hacker
title: Imminent-Darkness -- Security Research, Vulnerability Assessment, Exploit Development, Inconcealable Ambition for Red Team Orchestration!
description: Toss the resume aside for a minute and take a moment to peek under the hoodie.
