remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Imminent-Darkness
description: I enjoy studying for certifications that I can't afford an exam voucher for.  
