remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Imminent-Darkness
description: Effective security requires one to reflect on the most terrifying scenario and preparing for someone diabolical enough to execute it.
include: ['_pages']
markdown: kramdown
