theme: jekyll-theme-hacker
title: Imminent-Darkness: Security Research, Vulnerability Assessment, Exploit Development, Inconcealable Ambition for Red Team Orchestration!
description: If you are holding my resume right now, then you are in possession of significantly more Personally Identifiable Information than I am comfortable sharing on a web page. Toss the resume aside for a minute and take a moment to peek under the hoodie.
