theme: jekyll-theme-hacker  
title: Imminent-Darkness  
description: Security Research, Vulnerability Assessment, Exploit Development, Inconcealable Ambition for Red Team Orchestration!  
Toss the resume aside for a minute and take a moment to peek under the hoodie.
